### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/ssl-keygen#1]
Hello DB -- are you planning to continue work on this project? Is the aim for it to be universally useful, for Zalando-specific?

**Comment by dryewo** [comment]
Hello Lauri,
This project is done and is already universally useful. Nothing Zalando specific.

**Comment by lasomethingsomething** [comment]
Great. Let's chat soon about the README content -- I have a lot of projects to work on README-wise, but will put it in the queue.
